# Generated by Django 4.0.4 on 2022-05-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_images_images_car'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='СarModel',
            new_name='CarModel',
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(upload_to='brand_logos/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Имя категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.SlugField(max_length=300, verbose_name='Ссылка на категорию'),
        ),
    ]
