# Generated by Django 4.0.4 on 2022-05-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_сarmodel_carmodel_alter_brand_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
